spring.datasource.url=jdbc:postgresql://localhost:5432/academia_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.Dataicode.proyecto1=INFO
logging.file.name=logs/proyecto1.log

# Los archivos .gz los genera automaticamente Logback cuando se produce la rotacion de logs.
# Spring Boot usa Logback por defecto y al configurar logging.file.name el sistema empieza a escribir los logs en un archivo.
# Cuando el log cambia de dia, se rota o llega a un tamano especifico, Logback comprime el archivo antiguo en formato .gz